uploaded

diff --git a/.github/workflows/docker-build-and-deploy.yml b/.github/workflows/docker-build-and-deploy.yml
--- a/.github/workflows/docker-build-and-deploy.yml
+++ b/.github/workflows/docker-build-and-deploy.yml
@@ -3,7 +3,7 @@ name: Deploy to Server
 on:
   push:
     branches:
-      - main # Run this workflow when code is pushed to the main branch
+      - main
 
 jobs:
   deploy:
@@ -23,7 +23,7 @@ jobs:
         run: |
           sudo curl -L "https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
           sudo chmod +x /usr/local/bin/docker-compose
-          docker-compose --version  # Verify installation
+          docker-compose --version
 
       # Login to DockerHub
       - name: Login to DockerHub
@@ -32,10 +32,15 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
+      # Confirm existing containers
+      - name: List Docker containers
+        run: |
+          docker ps -a
+
       # Stop existing Docker containers using docker-compose
       - name: Stop existing containers
         run: |
-          docker-compose down
+          docker-compose down || echo "No resource found to remove"
 
       # Build and restart Docker Compose
       - name: Build and restart Docker Compose
@@ -46,4 +51,4 @@ jobs:
       # Optionally, restart Nginx service
       - name: Restart Nginx service
         run: |
-          docker-compose restart nginx
+          docker-compose restart nginx || echo "Nginx service not found"
